server:
    port: 8084
spring:
  application:
    name: API-GATEWAY
  config:
    import:
    -  "configserver:http://localhost:8085" 
#     spring.config.import= configserver:http://localhost:8085"
#  profiles:
#    active:
#    - default  

#Now Configuration here all my micro services here
  cloud:
    gateway:
      routes:
      - id: USER-SERVICE
        uri: lb://USER-SERVICE
        predicates:
        - Path=/users/**
        
      - id: HOTEL-SERVICE
        uri: lb://HOTEL-SERVICE
        predicates:
        - Path=/hotels/**,/staff/**
        
      - id: RATING-SERVICE
        uri: lb://RATING-SERVICE
        predicates:
        - Path=/ratings/**
        
#Okta Configuration
okta:
  oauth2:
    issuer: https://dev-01135178.okta.com/oauth2/default
    audience: api://default
    client-id: 0oa8asb83wsKPvHz55d7
    client-secret: x7BJljkVd3EbACyamVShN9sAW7e7_gnUHggybEdr
    scopes:
    - openid,profile,email,offline_access,phone,address
    
    
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka