#server:
#  port: 8085
#
#spring:
#  application:
#    name: CONFIG-SERVER
#  profiles:
#    active:
#    - native
#    
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/ddsha441981/Microservice-Config-Server
#          clone-on-start: true
#          default-label: main