server:
  port: 8761
  
spring:
  application:
    name: SERVICE-REGISTERY


  config:
    import:
    -  "configserver:http://localhost:8085" 
#     spring.config.import= configserver:http://localhost:8085"
#  profiles:
#    active:
#    - default  


#eureka:
#  instance:
#    hostname: localhost
#  client:
#    register-with-eureka: false
#    fetch-registry: false