#logging:
#  level:
#    '[com.cwc.user.service.external.service.HotelService]': debug #debug particular package
#feign:
#  client:
#    config:
#      default:
#        connect-timeout: 5000
#        read-timeout: 5000
#        logger-level: FULL
#      HotelService:
#        logger-level: FULL
        
        
server:
  port: 8081
  
spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: root
    dbcp2:
      driver-class-name: com.mysql.cj.jdbc.Driver
      
      
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    show-sql: true
    

  config:
    import:
    -  "configserver:http://localhost:8085" 
#     spring.config.import= configserver:http://localhost:8085"
#  profiles:
#    active:
#    - default


#Spring boot Actuator Configuration
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
     web:
       exposure:
         include: health
           
         
  endpoint:
    health:
      show-details: always
    info:
      enabled: true
      
#CircuitBreaker Resilience4j
resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 6s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: count-based
        
#Retry Resilience4j Configuration
  retry:
    instances:
      ratingHotelService:
        max-attempts: 3
        wait-duration: 3s
    
      


#Eureka Client Configuration
#eureka:
#  instance:
#    hostname: localhost
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
 
  
